apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "anchauhakscluster"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "anchauhakscluster"
    spec:
      containers:
        - name: "anchauhakscluster"
          image: ".azurecr.io/anchauhakscluster599c"
          ports:
          - containerPort: 80