apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "anchauhakscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "anchauhakscluster"
    spec:
      containers:
        - name: "anchauhakscluster"
          image: "anuragcontainerwebappacr.azurecr.io/anchauhaksclustera0c7"
          ports:
          - containerPort: 80