apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaaatiwarishubaks-64f6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaaatiwarishubaks-64f6"
  template:
    metadata:
      labels:
        app: "aaaaatiwarishubaks-64f6"
    spec:
      containers:
        - name: "aaaaatiwarishubaks-64f6"
          image: "anunewacr.azurecr.io/aaaaatiwarishubaks61be"
          ports:
          - containerPort: 80