apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "aaaaatiwarishubaks-eb88"
    labels:
        app: "aaaaatiwarishubaks-eb88"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: aaaaatiwarishub-aks98ab-aaaaatiwarishubaks-eb88.8f944e03c2724479b251.eastus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "aaaaatiwarishubaks-eb88"
                servicePort: 80