apiVersion: v1
kind: Service
metadata:
    name: vscodebugbash1
    labels:
        app: vscodebugbash1
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: vscodebugbash1