apiVersion: v1
kind: Service
metadata:
    name: "diaggarwtest-b893"
    labels:
        app: "diaggarwtest-b893"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "diaggarwtest-b893"
