apiVersion: v1
kind: Service
metadata:
    name: "diaggarwtest-5f0f"
    labels:
        app: "diaggarwtest-5f0f"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "diaggarwtest-5f0f"
