apiVersion: v1
kind: Service
metadata:
    name: "ajayaks12321-7016"
    labels:
        app: "ajayaks12321-7016"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "ajayaks12321-7016"