apiVersion: v1
kind: Service
metadata:
    name: "askbugbash-f015"
    labels:
        app: "askbugbash-f015"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "askbugbash-f015"