apiVersion: v1
kind: Service
metadata:
    name: "bugbash1622-dfaa"
    labels:
        app: "bugbash1622-dfaa"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bugbash1622-dfaa"