apiVersion: v1
kind: Service
metadata:
    name: anuragcacrbuildhelloworldnode
    namespace: anuragaksprod1181
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: anuragcacrbuildhelloworldnode
