apiVersion: v1
kind: Service
metadata:
    name: "bugbash1621-76fa"
    labels:
        app: "bugbash1621-76fa"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bugbash1621-76fa"