apiVersion: v1
kind: Service
metadata:
    name: "abcd-3302"
    labels:
        app: "abcd-3302"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "abcd-3302"