apiVersion: v1
kind: Service
metadata:
    name: "akstest3-0b4c"
    labels:
        app: "akstest3-0b4c"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akstest3-0b4c"