apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akskodey-f214"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akskodey-f214"
  template:
    metadata:
      labels:
        app: "akskodey-f214"
    spec:
      containers:
        - name: "akskodey-f214"
          image: "aksrivacr1.azurecr.io/akskodeyf214"
          ports:
          - containerPort: 80