apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akskodey-4af3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akskodey-4af3"
  template:
    metadata:
      labels:
        app: "akskodey-4af3"
    spec:
      containers:
        - name: "akskodey-4af3"
          image: "aksrivacr1.azurecr.io/akskodey4af3"
          ports:
          - containerPort: 80