on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: abhisheaacr.azurecr.io
        username: ${{ secrets.acr_abhisheaacr_username }}
        password: ${{ secrets.acr_abhisheaacr_password }}
    
#     - name: Build and push image to ACR
#       id: build-image
#       run: |
#         docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t abhisheaacr.azurecr.io/demotest:${{ github.sha }}
#         docker push abhisheaacr.azurecr.io/demotest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demotest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demotest2692 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demotest2692`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demotest2692
        container-registry-url: abhisheaacr.azurecr.io
        container-registry-username: ${{ secrets.acr_abhisheaacr_username }}
        container-registry-password: ${{ secrets.acr_abhisheaacr_password }}
        secret-name: demotestdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: demotest2692
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          abhisheaacr.azurecr.io/demotest:${{ github.sha }}
        imagepullsecrets: |
          demotestdockerauth
