on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: anuragcontainerwebappacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t anuragcontainerwebappacr.azurecr.io/anchauhakscluster5e04:${{ github.sha }}
        docker push anuragcontainerwebappacr.azurecr.io/anchauhakscluster5e04:${{ github.sha }}
    
    - uses: azure/k8s-actions/k8s-set-context@master
      with:
         kubeconfig: ${{ secrets.KUBE_CONFIG }}
      id: login
    
    - name:  create namespace
      run: |
        kubectl create namespace anchauhakscluster09d0

    - uses: azure/k8s-actions/k8s-create-secret@master
      with:
        namespace: anchauhakscluster09d0
        container-registry-url: anuragcontainerwebappacr.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME-07f6 }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: dockerAuthSecret
       
    - uses: azure/k8s-actions/k8s-deploy@master
      with:
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          anuragcontainerwebappacr.azurecr.io/anchauhakscluster5e04:${{ github.sha }}
        imagepullsecrets: |
          dockerAuthSecret
