on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets._9dd2}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n  -g  --location "" --sku  --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n  --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n  --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n  --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: .azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t .azurecr.io/akstest39dd2:${{ github.sha }}
        docker push .azurecr.io/akstest39dd2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_akstest3_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akstest39dd2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akstest39dd2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akstest39dd2
        container-registry-url: .azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: akstest3dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akstest39dd2
        manifests: |
          ./manifests/deployment-9dd2.yml
          ./manifests/service-9dd2.yml
        images: |
          .azurecr.io/akstest39dd2:${{ github.sha }}
        imagepullsecrets: |
          akstest3dockerauth