on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: 06cd9c503afa4455b32b81fb0da4d8ff.azurecr.io
        username: ${{ secrets.acr_06cd9c503afa4455b32b81fb0da4d8ff_username }}
        password: ${{ secrets.acr_06cd9c503afa4455b32b81fb0da4d8ff_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Do - cker" -f  "Do - cker/Dockerfile" -t 06cd9c503afa4455b32b81fb0da4d8ff.azurecr.io/aaaaatiwarishubaks:${{ github.sha }}
        docker push 06cd9c503afa4455b32b81fb0da4d8ff.azurecr.io/aaaaatiwarishubaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aaaaatiwarishubaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aaaaatiwarishhyijvb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aaaaatiwarishhyijvb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aaaaatiwarishhyijvb
        container-registry-url: 06cd9c503afa4455b32b81fb0da4d8ff.azurecr.io
        container-registry-username: ${{ secrets.acr_06cd9c503afa4455b32b81fb0da4d8ff_username }}
        container-registry-password: ${{ secrets.acr_06cd9c503afa4455b32b81fb0da4d8ff_password }}
        secret-name: aaaaatiwarisdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aaaaatiwarishhyijvb
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
          manifests/ingress-1.yml
        images: |
          06cd9c503afa4455b32b81fb0da4d8ff.azurecr.io/aaaaatiwarishubaks:${{ github.sha }}
        imagepullsecrets: |
          aaaaatiwarisdockerauth