on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: absfsf.azurecr.io
        username: ${{ secrets.acr_absfsf_username }}
        password: ${{ secrets.acr_absfsf_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Do - cker" -f  "Do - cker/Dockerfile" -t absfsf.azurecr.io/diaggarwtest:${{ github.sha }}
        docker push absfsf.azurecr.io/diaggarwtest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_diaggarwtest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep diaggarw-test96b3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace diaggarw-test96b3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: diaggarw-test96b3
        container-registry-url: absfsf.azurecr.io
        container-registry-username: ${{ secrets.acr_absfsf_username }}
        container-registry-password: ${{ secrets.acr_absfsf_password }}
        secret-name: diaggarwtestdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: diaggarw-test96b3
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          absfsf.azurecr.io/diaggarwtest:${{ github.sha }}
        imagepullsecrets: |
          diaggarwtestdockerauth