on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_GITHUB_SECRET_4065}}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n testacr -g test-rg --location "South Central US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n testacr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n testacr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n testacr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: testacr.azurecr.io
        username: ${{steps.create-acr.outputs.acr_username}}
        password: ${{steps.create-acr.outputs.acr_password}}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t testacr.azurecr.io/testcluster4065:${{github.sha}}
        docker push testacr.azurecr.io/testcluster4065:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{secrets.aks_testcluster_kubeConfig}}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testcluster4065 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testcluster4065`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testcluster4065
        container-registry-url: testacr.azurecr.io
        container-registry-username: ${{steps.create-acr.outputs.acr_username}}
        container-registry-password: ${{steps.create-acr.outputs.acr_password}}
        secret-name: testclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testcluster4065
        manifests: |
          ./manifests/deployment-4065.yml
          ./manifests/service-4065.yml
        images: |
          testacr.azurecr.io/testcluster4065:${{github.sha}}
        imagepullsecrets: |
          testclusterdockerauth