on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
   - name: Create ACR
      id: create-acr
      run: |
        az acr create -n anunewacr -g anuragDevOpsaks-rg --location East US --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n anunewacr --query username`"
        echo "::set-output name=acr_passwrod::`az acr credential show -n anunewacr --query passwords[0].value`"

    - uses: azure/docker-login@v1
      with:
        login-server: anunewacr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build . -t anunewacr.azurecr.io/anchauhakscluster4d9b:${{ github.sha }}
        docker push anunewacr.azurecr.io/anchauhakscluster4d9b:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_anchauhAksCluster_kubeConfig }}
    
    - name: create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep anchauhaksclusterc16e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace anchauhaksclusterc16e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: anchauhaksclusterc16e
        container-registry-url: anunewacr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password:  ${{ steps.create-acr.outputs.acr_password }}
        secret-name: anchauhakscldockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: anchauhaksclusterc16e
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          anunewacr.azurecr.io/anchauhakscluster4d9b:${{ github.sha }}
        imagepullsecrets: |
          anchauhakscldockerauth