on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: anchauhakstest.azurecr.io
        username: ${{ secrets.acr_anchauhakstest_username }}
        password: ${{ secrets.acr_anchauhakstest_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t anchauhakstest.azurecr.io/bugbash1621:${{ github.sha }}
        docker push anchauhakstest.azurecr.io/bugbash1621:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bugbash1621_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep bugbash1621d437 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace bugbash1621d437`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: bugbash1621d437
        container-registry-url: anchauhakstest.azurecr.io
        container-registry-username: ${{ secrets.acr_anchauhakstest_username }}
        container-registry-password: ${{ secrets.acr_anchauhakstest_password }}
        secret-name: bugbash1621dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: bugbash1621d437
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          anchauhakstest.azurecr.io/bugbash1621:${{ github.sha }}
        imagepullsecrets: |
          bugbash1621dockerauth