# Plain Node.js on Linux Web App
# Build a plain Node.js project and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - master

name: Build and deploy Plain Node.js on Linux Web App

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    # login using azure credentials
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_GITHUB_SECRET_1686}}

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    # install dependencies, build, and test
    - name: npm install, build, and test
      working-directory: .
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - uses: azure/appservice-settings@v1
      with:
        app-name: aaaatiwarishub-webapp-linux
        general-settings-json: '{"linuxFxVersion": "NODE|14-lts"}' #'General configuration settings as Key Value pairs'

    # deploy web app
    - uses: azure/webapps-deploy@v1
      with:
        app-name: aaaatiwarishub-webapp-linux
        package: .

    # Azure logout
    - name: logout
      run: |
        az logout